### ISSUE TITLE
ESP32 Support

### ISSUE THREAD

**Issue by cw2** [nanoframework/nf-interpreter#136]
I am happy to announce that ESP32 support is now under active development.

The implementation is based on the official [Espressif IoT Development Framework](https://github.com/espressif/esp-idf) (ESP-IDF), initially for a generic [ESP-WROOM-32](https://espressif.com/en/producttype/esp-wroom-32) module.

The following is a rough roadmap:

- [x] Initial experiments (toolchain setup, build environment, deployment, debugging, diagnostics)
- [ ] nanoBooter port
  - [ ] :question: implement as a part of 2nd stage bootloader or a separate [3rd stage] ?
- [ ] :running_man: nanoCLR port

> Note: The nanoCLR is being done now (before bootloader) to synchronize with ongoing ChibiOS HAL work.

ESP-IDF has many features that make it very good fit for nanoFramework (the list is not complete, and in no particular order of importance):
- GCC-based toolchain,
- Highly componentized and customizable build system,
- Bootloader is a separate application,
- Customizable flash memory partition table,
- Over-the-air updates

**Comment by josesimoes** [comment]
👏  👏   👏

**Comment by piwi1263** [comment]
👏👏👏

If you need a hand in testing out or if you need a guinnee pig just let me know ....

**Comment by josesimoes** [comment]
Could you please confirm if this actually _in progress_ or not?
