### ISSUE TITLE
Work on Monitor_FlashSectorMap 

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/nf-interpreter#382]
nanoBooter is not being able to report the Flash map because the code in the command is commented in WireProtocol_MonitorCommands.c.

Uncomment and follow the implementation of CLR_DBG_Debugger::Monitor_FlashSectorMap to make it work

**Comment by networkfusion** [comment]
Uncommented Monitor_FlashSectorMap in targets/CMSIS-OS/ChibiOS/nanoBooter/WireProtocol_MonitorCommands.c however it fails with BlockStorageDevice* being undefined.

**Comment by MikroBusNet** [comment]
What if you include this file : nf-interpreter\src\PAL\Include\nanoPAL_BlockStorage.h ?

**Comment by networkfusion** [comment]
that just causes: 'BlockStorageDevice {aka struct BLOCKSTORAGEDEVICE}' has no member named 'GetDeviceInfo'
